import type { LucideIcon } from "lucide-react";
import {
  AppWindow,
  BookOpen,
  Braces,
  Brain,
  Calendar,
  ChartColumn,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  Flag,
  FlaskConical,
  Gift,
  GitBranch,
  Handshake,
  Image,
  Layers,
  Library,
  Lightbulb,
  Magnet,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  MousePointerClick,
  Network,
  Newspaper,
  NotebookPen,
  Palette,
  PenLine,
  Repeat,
  Rocket,
  ScanSearch,
  Scissors,
  Search,
  Send,
  Smartphone,
  Sparkles,
  Swords,
  Tag,
  Target,
  UserMinus,
  UserPlus,
  Users,
  UsersRound,
  Video,
  Workflow,
  Wrench,
} from "lucide-react";
import type { SkillIcon } from "@/data/packs";

export const skillIcons: Record<SkillIcon, LucideIcon> = {
  megaphone: Megaphone,
  users: Users,
  "mouse-pointer-click": MousePointerClick,
  "user-plus": UserPlus,
  rocket: Rocket,
  "message-square": MessageSquare,
  "credit-card": CreditCard,
  "pen-line": PenLine,
  scissors: Scissors,
  mail: Mail,
  send: Send,
  "message-circle": MessageCircle,
  smartphone: Smartphone,
  image: Image,
  video: Video,
  tag: Tag,
  search: Search,
  sparkles: Sparkles,
  layers: Layers,
  network: Network,
  swords: Swords,
  "scan-search": ScanSearch,
  braces: Braces,
  "app-window": AppWindow,
  "notebook-pen": NotebookPen,
  palette: Palette,
  calendar: Calendar,
  handshake: Handshake,
  "chart-column": ChartColumn,
  "flask-conical": FlaskConical,
  "git-branch": GitBranch,
  gift: Gift,
  "user-minus": UserMinus,
  wrench: Wrench,
  "users-round": UsersRound,
  magnet: Magnet,
  repeat: Repeat,
  "clipboard-list": ClipboardList,
  lightbulb: Lightbulb,
  brain: Brain,
  "messages-square": MessagesSquare,
  flag: Flag,
  "circle-dollar-sign": CircleDollarSign,
  newspaper: Newspaper,
  workflow: Workflow,
  "book-open": BookOpen,
  target: Target,
  library: Library,
};
